### ISSUE TITLE
Need to add environment variables for xpack settings

### ISSUE THREAD

**Issue by ctindel** [elastic/kibana-docker#10]
xpack Settings like xpack.security.secureCookies etc are not available to set via environment variables.  Here's a list:

https://www.elastic.co/guide/en/x-pack/current/kibana.html

It's not clear whether these settings are settable on the CLI like the other settings.  May need to check with kibana team, and if so open a ticket with them to add the settings to the CLI as well?

**Comment by jarpy** [comment]
Fixed in 7f40ee01cb08aba3fbd6e5676f7cb1d7e8fd38ec.

New image for `docker.elastic.co/kibana/kibana:5.1.1` is now live on the registry.

This is probably important enough to backport to 5.0.

**Comment by weltenwort** [comment]
How about defining a general environment variable like `KIBANA_OPTS` the content of which is appendend to the Kibana commandline? That way every option not listed in the wrapper script can be specified using `docker run [...] -e "KIBANA_OPTS=--myplugin.foo"  [...]`.

**Comment by eperdeme** [comment]
This is missing stuff like;

xpack.monitoring.elasticsearch.url
xpack.monitoring.elasticsearch.username
xpack.monitoring.elasticsearch.password

Is this by design or just need adding ?

**Comment by jarpy** [comment]
Definetly not by design! Thanks for the report, @eperdeme.

Fixed in c60f30f5149f851acaabd8ef6b1bc74a58e04882.

Updated image pushed to `docker.elastic.co/kibana/kibana:5.2.0`.
