### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by dynek** [elastic/kibana-docker#11]
Hello,

Is anyone really using this image?
The x-pack plugin is installed as root then user context switches to kibana but some files in /usr/share/kibana/optimize/ remain owned by root and causes service startup to fail with
```
Error: EACCES: permission denied, open '/usr/share/kibana/optimize/bundles/graph.entry.js'
```
Tried 5.0.1 and 5.1.1

Note: it seems to be happening only if SERVER_BASEPATH is being specified.

Thank you

**Comment by jarpy** [comment]
Thanks for the report.

It seems there's an [upstream issue in Kibana](https://github.com/elastic/kibana/issues/8818) that details the problem. I'll track that issue and figure out the best fix for the Docker image.

**Comment by jarpy** [comment]
Fixed in 199b9ed85c2db73010dc4ac70be716cf7283d616. Will backport and push new images for:

- [ ] 5.1.1
- [ ] 5.0.2
- [ ] 5.0.1
- [ ] 5.0.0

**Comment by dynek** [comment]
Excellent! Thanks for the quick fix.

**Comment by Madhu1512** [comment]
I am seeing same issue in 5.1.2 image but not with 5.1.1. Is 5.1.2 image updated with your fix?

**Comment by jarpy** [comment]
Good catch.

Somehow this has regressed in 5.1.2:

```
$ docker run -it docker.elastic.co/kibana/kibana:5.1.2 stat -c%U /usr/share/kibana/optimize/bundles/graph.entry.js
root

$ docker run -it docker.elastic.co/kibana/kibana:5.1.1 stat -c%U /usr/share/kibana/optimize/bundles/graph.entry.js
kibana
```

Apologies. Let me figure out what went wrong.

**Comment by jarpy** [comment]
I've now pushed a corrected image.

Thanks for the report, and sorry for the trouble.
