### ISSUE TITLE
Support spaces in environment variables?

### ISSUE THREAD

**Issue by spalger** [elastic/kibana-docker#118]
Based on https://github.com/elastic/kibana-docker/blob/master/.tedi/template/kibana-docker#L159 it looks like none of the environment variables that are converted into CLI arguments support spaces, is that right? Specifically seeing issues with the `ELASTICSEARCH_PASSWORD` var, but it looks like it probably isn't the only one.

**Comment by jarpy** [comment]
That looks correct to me. Throwing some single-quotes around the value would probably clean things up.

We also needs tests like the [ones for Logstash](https://github.com/elastic/logstash-docker/blob/master/tests/test_settings.py).

**Comment by cyinll** [comment]
i need use space in `elasticsearch.customHeaders`, it failed
```
docker run --name kibana -p 5601:5601 -e SERVER_HOST="0.0.0.0" -e ELASTICSEARCH_URL="http://11.163.30.154:12345" -e ELASTICSEARCH_CUSTOMHEADERS='{"kibana-version":"6.4.3","Authorization":"Basic dGhpc19pc19hX3Rlc3Q6T2MyYTMxM2FhYWVkNw=="}' docker.elastic.co/kibana/kibana-oss:6.4.3
```

**Comment by cyinll** [comment]
> That looks correct to me. Throwing some single-quotes around the value would probably clean things up.
> 
> We also needs tests like the [ones for Logstash](https://github.com/elastic/logstash-docker/blob/master/tests/test_settings.py).

i need use space in `elasticsearch.customHeaders`, it failed

```
docker run --name kibana -p 5601:5601 -e SERVER_HOST="0.0.0.0" -e ELASTICSEARCH_URL="http://11.163.30.154:12345" -e ELASTICSEARCH_CUSTOMHEADERS='{"kibana-version":"6.4.3","Authorization":"Basic dGhpc19pc19hX3Rlc3Q6T2MyYTMxM2FhYWVkNw=="}' docker.elastic.co/kibana/kibana-oss:6.4.3
```

**Comment by jbudz** [comment]
Migrating this over to https://github.com/elastic/kibana/issues/39594.  We'll be tracking docker issues in the kibana repo going forward.
