### ISSUE TITLE
Kibana variable `elasticsearch.hosts` not supported in 6.6.0 BC6 docker image

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/kibana-docker#120]
In version 6.6, Kibana seem to have changed `elasticsearch.url` to `elasticsearch.hosts`. When using the docker image released as part of version 6.6.0 BC6 it seems the docker image does not pick up `ELASTICSEARCH_HOSTS` and still expects `ELASTICSEARCH_URL` (which I am not sure kibana will pay any attention any longer).

**Comment by mistic** [comment]
Should be closed by https://github.com/elastic/kibana-docker/pull/121
