### ISSUE TITLE
Userns-Remap issue permission denied

### ISSUE THREAD

**Issue by henri9813** [elastic/kibana-docker#136]
Hello,

My problem is the same that this issue: https://github.com/elastic/kibana-docker/issues/92

Here is my `/etc/docker/daemon.json`:
```
{
  "userns-remap": "henri"
}
```
```
henri@henri-iMac:~$ cat /etc/subgid
henri:1000:65536
henri@henri-iMac:~$ cat /etc/subuid
henri:1000:65536
```

Here is the traceback of the run command that you did in the mentioned issue

```
henri@henri-iMac:~/GolandProjects/godalf$ docker run --rm -it -e ELASTICSEARCH_URL=http://elasticsearch1:9200 docker.elastic.co/kibana/kibana:6.3.2
Unable to find image 'docker.elastic.co/kibana/kibana:6.3.2' locally
6.3.2: Pulling from kibana/kibana
7dc0dca2b151: Pull complete 
8ce241372bf3: Pull complete 
d6671bb44c0a: Pull complete 
f3522d60bffe: Pull complete 
e4d56fe4aebf: Pull complete 
68df91c3f85d: Pull complete 
aef1ffed878c: Pull complete 
c5aeceb9f680: Pull complete 
af84d3e72ccf: Pull complete 
Digest: sha256:7ae0616a5f5ddfb0f93ae4cc94038afd2d4e45fa7858fd39c506c8c682ee71f0
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:6.3.2
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/share/kibana/optimize/.babelcache.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at save (/usr/share/kibana/node_modules/babel-register/lib/cache.js:45:16)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

What can i do ? 

Best regards

**Comment by soullivaneuh** [comment]
Same issue here, I did apply this solution for file rights mapping: https://stackoverflow.com/a/49600083/1731473

@jarpy when you tried to reproduce #92, did you modify the `/etc/subuid` and `/etc/subgid` files? Of course, a docker service restart is required after the modification of those file and the config one to make it working.

Regards

**Comment by jarpy** [comment]
Yes. I created them.

This looks suspicious:

```
henri@henri-iMac:~$ cat /etc/subgid
henri:1000:65536
henri@henri-iMac:~$ cat /etc/subuid
henri:1000:65536
```

That's remapping to a UID range starting at `1000`. Isn't that the same range that the host system uses anyway?

**Comment by jarpy** [comment]
Also, I see the string `henri-iMac`. Just out of curiosity, what operating system is this host running?

**Comment by henri9813** [comment]
Hello,

I'm on ubuntu :-)
( Ubuntu on iMac, that's the power ! )

**Comment by soullivaneuh** [comment]
> Isn't that the same range that the host system uses anyway?

Yes, and it is the only way we found to make it working. Let the range to `10000` just make docker not working with ownership assignation.

So far, it caused not trouble on any docker image except this one, that's pretty odd.

**Comment by jarpy** [comment]
To me, the primary purpose of `userns-remap` is run processes in an isolated range of UIDs. If you "remap" them into the existing range that is already used by processes on the host system, then what is gained? Can you help me understand why you want to remap UIDs back into a range that clashes with an existing one?

The [Docker documentation](https://docs.docker.com/engine/security/userns-remap/) is full of phrases like:

> It is very important that the ranges not overlap, so that a process cannot gain access in a different namespace.

**Comment by jarpy** [comment]
> So far, it caused not trouble on any docker image except this one, that's pretty odd.

Could you provide some examples of other images? A lot of publicly available images run as UID 0, against best-practice. We don't do that. I wonder if it's a factor?

**Comment by jbudz** [comment]
Migrating this over to https://github.com/elastic/kibana/issues/39602
