### ISSUE TITLE
Error: is unauthorized for user

### ISSUE THREAD

**Issue by leobaiano** [elastic/kibana-docker#137]
I have an elastic search running on an instance of AWS and a kibana also connecting there.

I'm trying to work with kibana locally, but accessing the elastic search online, to start my studies on development of kibana plugins and customization.

That said, I cloned this repository and created a `docker-compose.yml` inside it with the settings below:

```
version: '2'
services:
  kibana
    image: docker.elastic.co/kibana/kibana:6.5.4
    environment:
      SERVER_NAME: kibana.localhost
      ELASTICSEARCH_URL: https: // server-online: 9243
      ELASTICSEARCH_USERNAME: user
      ELASTICSEARCH_PASSWORD: pass
      ELASTICSEARCH_HOSTS: https: // server-online: 9243
```

When I run `docker-compose up` everything seems to be fine but at the end I get the following error message:

```
FATAL [security_exception] action [indices: admin / get] is unauthorized for user [developer] :: {"path": "/. Kibana", "query": {}, "statusCode": 403, {\ "error \": {\ "root_cause \": [{\ "type \": \ "security_exception \", \ "reason \": \ "action [indices: admin / get] is unauthorized for user [developer ] \ "type \": \ "security_exception \", \ "reason \": \ "action [indices: admin / get] is unauthorized for user [developer] : 403} "}
```

Initially when accessing `https: // server-online: 9243 'myindex` and connecting with the user and password I am using in the` .yml` configuration I received the same error, so I gave super superuser permission to it and via browser started to work, but when I try to raise the kibana by `docker-compose` I still get the error.

**Comment by tylersmalley** [comment]
If you're wanting to develop for Kibana, why not work with the Kibana repository directly? There is a [contributing guide](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md) to help you out. There are also tools there to assist with standing up a local Elasticsearch cluster to develop against.

**Comment by leobaiano** [comment]
Thanks for the reply @tylersmalley 

I thought it would not make any difference and I ended up opting for the docker, but do you think this problem has anything to do with it?

**Comment by tylersmalley** [comment]
The docker builds are for deployment, not for development. If you are developing against Kibana you really want to be running it from source.

**Comment by tylersmalley** [comment]
And in regards to the error, you're seeing - it's due to not having access to the `.kibana` index.

> FATAL [security_exception] action [indices: admin / get] is unauthorized for user [developer] :: {"path": "/. Kibana", "query": {}, "statusCode": 403, {\ "error \": {\ "root_cause \": [{\ "type \": \ "security_exception \", \ "reason \": \ "action [indices: admin / get] is unauthorized for user [developer ] \ "type \": \ "security_exception \", \ "reason \": \ "action [indices: admin / get] is unauthorized for user [developer] : 403} "}


I am also going to close out this issue.  We reserve Github Issues for bug reports and feature requests. If you have questions, feel free to post your question to https://discuss.elastic.co/c/kibana
