### ISSUE TITLE
Support _FILE environment variable?

### ISSUE THREAD

**Issue by TJM** [elastic/kibana-docker#139]
We are trying to run Kibana in DDC (sigh) and the *secrets* are mounted as files, and thus the "secret" has to be read from `/run/secrets/secret-name`. The "workaround" for this issue in DDC is to  create a wrapper script that reads the secret and puts the value into the correct env variable.

I propose that the "helper" script could look for SOME_VAR_FILE, and if it finds that (and its a file thats readable), put the contents of the file into SOME_VAR.

The places I see this being most useful is "ELASTICSEARCH_PASSWORD" and maybe "SERVER_SSL_KEYPASSPHRASE" as the other places I would use a "secret" are already looking for a file.

Suggestions?

~tommy

**Comment by jbudz** [comment]
Hey - we're migrating issues over to the kibana repo so I reopened this at https://github.com/elastic/kibana/issues/39605.
