### ISSUE TITLE
xpack.uptime.enabled & xpack.maps.enabled missing

### ISSUE THREAD

**Issue by jguay** [elastic/kibana-docker#141]
Currently in [kibana-docker v6.x](https://github.com/elastic/kibana-docker/blob/6.x/build/kibana/bin/kibana-docker) the following settings are missing:
- xpack.uptime.enabled
- xpack.maps.enabled

Those settings are pending official documentation but work fine per https://github.com/elastic/kibana/issues/36156

As a result, environment variable "XPACK_UPTIME_ENABLED=false" and "XPACK_MAPS_ENABLED=false" have no effect in 6.7.x or 6.8.0 (also up to current 7.1.1)

Workaround : Adding "xpack.uptime.enabled: false" and "xpack.maps.enabled: false" in kibana.yml works as expected (removing the options from the menu)

**Comment by jbudz** [comment]
Thanks @jguay, migrating this over to https://github.com/elastic/kibana/issues/39592.
