### ISSUE TITLE
Alpine version

### ISSUE THREAD

**Issue by ddeboer** [elastic/kibana-docker#15]
An Alpine version would be great to have a smaller image, particularly since the new Kibana image is much bigger than the deprecated one from Docker Hub:

```
docker.elastic.co/kibana/kibana   5.2.2                 632182dfaaf7        674 MB
kibana                            5.0                   e670e64ab06e        321 MB
```

**Comment by jarpy** [comment]
Hi @ddeboer,

I agree that it would be good to have a smaller image if possible. When we started the Kibana image, we actually began with Alpine as the base, but the absence of some packages was problematic for us. In particular, the [reporting feature](https://www.elastic.co/guide/en/x-pack/5.2/xpack-reporting.html) from X-Pack depends on PhantomJS, which is [not available as an Alpine package](https://bugs.alpinelinux.org/issues/4664).

So, for the time being, we intend to stay with a "fatter" base image for Kibana. For the 6.0 release, however, we do plan to increase the number of layers shared between the various Elastic Stack images, to save a little disk space for people who have multiple images pulled on the same host.
