### ISSUE TITLE
Reporting doesn't work in kibana docker image?

### ISSUE THREAD

**Issue by ctindel** [elastic/kibana-docker#16]
I don't know if there's something special I need to do for setting this up but when I go into reporting I get an error.  See screenshot.

<img width="2469" alt="kibana_docker_reporting_error" src="https://cloud.githubusercontent.com/assets/1863749/24153899/09b32920-0e26-11e7-8de6-97bdd55c5479.png">

CC @jarpy

**Comment by jarpy** [comment]
I can't replicate this with a fresh [stack-docker](https://github.com/elastic/stack-docker/blob/master/docker-compose.yml) example stack.

Is there some kind of key material that is not being persisted due to the Docker environment?

Do you have any flashes of insight here, @ycombinator? Thanks.

**Comment by ctindel** [comment]
@jarpy can you try it with an elastic cloud ES instance but pointing a docker kibana instance at that and see if anything goes wrong? Also this cloud instance was created as 5.0 and upgraded through 5.1 to 5.2 so I wonder if there's some weirdness there.

If you go to https://sa-demo-honeypot-kibana.dev.sa.elastic.co you can see the error probably.

**Comment by jarpy** [comment]
I think a more expedient replication attempt would be for you to run a non-containerised Kibana, of the same version, against your data source.

**Comment by ctindel** [comment]
Hmmm yes good point I will try that!

**Comment by ycombinator** [comment]
> Is there some kind of key material that is not being persisted due to the Docker environment?

Yes, this error happens when `xpack.reporting.encryptionKey` is not set in `kibana.yml`. In such cases, a random value is assigned upon Kibana server restart, which means reports encrypted with the previous key will not be able to be decrypted with the new key. Hope that helps.

**Comment by jarpy** [comment]
Thanks. @ycombinator. That's _really_ helpful.

So, the key is either completely stateless (in RAM), or persisted by declaring it in `kibana.yml`. No auto-persistence of the generated key to disk?

I ask because disk persistence gets ...interesting under Docker.

**Comment by ctindel** [comment]
@jarpy is it something we ought to be including as a docker startup variable like we do with the kibana index etc?

Honestly I have no idea how this reporting encryption stuff works I just saw the failed reports in our demo environments.

**Comment by ycombinator** [comment]
> So, the key is either completely stateless (in RAM), or persisted by declaring it in kibana.yml. No auto-persistence of the generated key to disk?

AFAIK, that's correct. However, it's been a while since I worked on Reporting so I'll let @kobelb confirm.

**Comment by jarpy** [comment]
Thanks.

It's already [included](https://github.com/elastic/kibana-docker/blob/c2ad97e2879ce89957b94ac635b445fa8170129a/build/kibana/bin/kibana-docker#L56), @ctindel, but it could certainly have some more attention drawn to it in the docs.

The shorter life of containerised processes tends to "enhance" these kinds of challenges.

**Comment by ctindel** [comment]
@jarpy I thought we were talking about xpack.reporting.encryptionKey the link you provided was for xpack.security.encryptionKey.  Are those aliases to the same thing or do we need to add the reporting one to the docker image?

**Comment by jarpy** [comment]
Oops, you are absolutely right! Thanks!

**Comment by kobelb** [comment]
@jarpy - @ycombinator is right that the xpack.reporting.encryptionKey isn't persisted to disk and handing it the same way that the xpack.security.encryptionKey is handled should resolve any issues.

**Comment by jarpy** [comment]
Fixed in a049365c3744052f21c541dd1372c60a8c61f6ed.

**Comment by ctindel** [comment]
@jarpy what version is this fixed in, 5.3.1 or do we need to wait for 5.3.2?

**Comment by jarpy** [comment]
Actually, it's [backported all the way to 5.0.0](https://github.com/elastic/kibana-docker/blob/5.0/build/kibana/bin/kibana-docker#L87). Enjoy! :beers:
