### ISSUE TITLE
Some settings changed in 5.3.0

### ISSUE THREAD

**Issue by johtani** [elastic/kibana-docker#19]
Some setting names changed in 5.3.0, see https://github.com/elastic/kibana/pull/9823
However, kibana-docker/build/kibana/bin/kibana-docker didn't update.

**Comment by jarpy** [comment]
Pushed a replacement image with support for the new options.

Image ID: `42982e10d4b9`

**Comment by jarpy** [comment]
I made the changes in 9dcc695 based on the comments in in elastic/kibana#9823, but looking at the patch itself, and the current default `kibana.yml`, more changes are needed. Thus 317fec4, 116b180.

Pushed a replacement image.

Image ID: `9dd8ffc6f4c1`
