### ISSUE TITLE
'Error' service - kibana failed to build

### ISSUE THREAD

**Issue by viztastic** [elastic/kibana-docker#2]
I get the following error when I attempt to "docker-compose up" on the 5.0 branch:

![image](https://cloud.githubusercontent.com/assets/8556736/18990838/1a7d0ea6-8758-11e6-819b-2a6aff7ac8dd.png)

Any thoughts @jarpy @dliappis ?

**Comment by dliappis** [comment]
@viztastic Are you trying to build a local image of Kibana yourself? If not, you can use our public images; an example can be found [in our blog article](https://www.elastic.co/blog/releasing-beta-version-of-elastic-docker-images). If yes, then `docker-compose.yml` expects an environment variable set to the Kibana version, so you should either:

- `make build`
or
```shell
export KIBANA_VERSION=5.0.0-beta1
docker-compose up
```

Hope that helps.

**Comment by jarpy** [comment]
Closing to keep things tidy. Please re-open if you need any more help.
