### ISSUE TITLE
Retaining editing saved objects by bind mounted volume?

### ISSUE THREAD

**Issue by carn1x** [elastic/kibana-docker#21]
Is it possible to retain Saved Objects in Kibana by bind mounting a volume, similar to how Elasticsearch data is retained? Or is the only way to retain such configuration to perform manual export/import? Thanks!

**Comment by jarpy** [comment]
Hi @carn1x,

As far as I know, Kibana keeps all its state in Elasticsearch, specifically in the `.kibana`index. There should be no need to preserve any state on the local file system of the Kibana containers. Try saving a visualisation, then destroying and recreating the Kibana container. I think you'll be pleasantly surprised!

**Comment by carn1x** [comment]
Ahh great, thanks!
