### ISSUE TITLE
Kibana not able to Access ElasticSearch

### ISSUE THREAD

**Issue by waytoharish** [elastic/kibana-docker#22]
Hi,
We able to access ElasticSerch in Browser through http://ip of dcoker:9200/

But When Kibana is running it giving bellow error-
![image](https://cloud.githubusercontent.com/assets/5119613/24649996/74972df6-1946-11e7-9b5a-ae23122d7f86.png)

**Comment by jarpy** [comment]
Without knowing anything about your configuration, it's impossible to say what's missing. I'm sorry. There will be some configuration in your system that is not doing what you expect it to.

It might a good idea to share your configuration with the community at the [Kibana forum](https://discuss.elastic.co/c/kibana), trying to include as much information as possible. Here at GitHub, only a couple of people will see your question, and GitHub issues aren't really the right place for tutorial-style help. They are really for reporting bugs in the product.

Thanks.
