### ISSUE TITLE
Switch Kibana Docker image to use alpine linux

### ISSUE THREAD

**Issue by margussipria** [elastic/kibana-docker#29]
Official Elasticsearch Docker image is using Alpine linux, it's size is 164 MB, Kibana uses Ubuntu with size of 678 MB. 

At least use -slim ubuntu, even compressed size for that is half what normal version has.

**Comment by jarpy** [comment]
Hi, 

Alpine Linux doesn't provide support for some features of Kibana and has introduced subtle bugs in some of our other products. We'll actually be standardizing on a Centos 7 base soon.

See #15, elastic/elasticsearch-docker/issues/44, elastic/logstash/issues/6043.
