### ISSUE TITLE
Problem pulling kibana 5.4.0 from docker for Mac 

### ISSUE THREAD

**Issue by cvaldess** [elastic/kibana-docker#32]
Mac OS Sierra 10.12.4 
Docker Version 17.03.1-ce-mac5 (16048)
Channel: stable
b18e2a50cc
docker-compose version 1.11.2, build dfed245

stack-docker < docker-compose up
Creating network "stackdocker_stack" with the default driver
Pulling kibana (docker.elastic.co/kibana/kibana:5.4.0)...
5.4.0: Pulling from kibana/kibana
59e69571f6c7: Already exists
1d183283a292: Pull complete
cb96f1762d96: Downloading [========================>  Take long time  ] 34.06 MB/52.9 MB
443c0035bf3c: Download complete
44521dcfe57b: Download complete
b5ed3e53dd29: Download complete
7e6ba66696b9: Download complete
64f9b10fdaa1: Download complete
ERROR: for create_logstash_index_pattern  Container "8987df0a59c5" is unhealthy.
ERROR: for import_dashboards  Container "8987df0a59c5" is unhealthy.
ERROR: for set_default_index_pattern  Container "8987df0a59c5" is unhealthy.
ERROR: Encountered errors while bringing up the project.
< docker ps
8987df0a59c5        docker.elastic.co/kibana/kibana:5.4.0                 "/bin/sh -c /usr/l..."   18 minutes ago      Up 18 minutes (unhealthy)   127.0.0.1:5601->5601/tcp             stackdocker_kibana_1

**Comment by jarpy** [comment]
Hi,

The images are served from Amazon S3 and CloudFront, so you may have had a poor network path to your CloudFront PoP at the time.

I'd suggest trying:

`docker pull docker.elastic.co/kibana/kibana:5.4.0`

separately from the `docker-compose up` step.

**Comment by xeraa** [comment]
I cannot really reproduce that with the same Mac OS X version (10.12.4) and the same Docker version (17.03.1-ce-mac5 (16048)) — note that my hashes are different since we've rebuilt the Kibana image yesterday:

```
$ uname -a
Darwin Philipp.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

$ docker pull docker.elastic.co/kibana/kibana:5.4.0
5.4.0: Pulling from kibana/kibana
59e69571f6c7: Already exists 
c414463dd4cc: Pull complete 
82dca101bc47: Pull complete 
bdec037a3e82: Pull complete 
fee06b005ae5: Pull complete 
b790825932ac: Pull complete 
ad97a6066b2b: Pull complete 
8e27e64fc4f1: Pull complete 
6e075528dd97: Pull complete 
Digest: sha256:96baba6c5312c29dc2d65ad0b54a5afb58bcd6c9562e1737e495dba83054a68e
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:5.4.0
```

I might misread your error message, but `8987df0a59c5 docker.elastic.co/kibana/kibana:5.4.0 "/bin/sh -c /usr/l..." 18 minutes ago Up 18 minutes (unhealthy) 127.0.0.1:5601->5601/tcp stackdocker_kibana_1` sounds as if you had the image, it's just not starting up correctly. You might need to give Docker a bit more memory; in my experience that's the number one reason for failures when you try to bring up the entire stack.

Also for the reference — these are the images I have. What does your list look like?

```
$ docker images
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
docker.elastic.co/kibana/kibana                 5.4.0               e4fe4d5612a2        21 hours ago        639 MB
docker.elastic.co/beats/packetbeat              5.4.0               1ea496db3b82        5 days ago          283 MB
docker.elastic.co/beats/metricbeat              5.4.0               2a9e98f038ce        5 days ago          262 MB
docker.elastic.co/beats/heartbeat               5.4.0               59c73cd9ca6f        5 days ago          266 MB
docker.elastic.co/beats/filebeat                5.4.0               49fcd694363c        5 days ago          253 MB
docker.elastic.co/logstash/logstash             5.4.0               8698b18c90b6        5 days ago          527 MB
docker.elastic.co/elasticsearch/elasticsearch   5.4.0               4c093701c312        5 days ago          524 MB
```

**Comment by jarpy** [comment]
> there are problems with the image for mac os

Docker images are universal. There is no specific image for MacOS.

**Comment by jarpy** [comment]
Maybe send the complete output of `docker pull docker.elastic.co/kibana/kibana:5.4.0`?

Thanks.

**Comment by jarpy** [comment]
@xeraa, the pull works for you, cool. :)

But, are you able to bring up stack-docker?

**Comment by xeraa** [comment]
I tested it right after the 5.4.0 release and it worked. However, I've given Docker more resources — otherwise I used to run into unhealthy Kibana instances as well.

![advanced 2017-05-10 03-15-38](https://cloud.githubusercontent.com/assets/432211/25878985/00782c9a-352f-11e7-933b-bf0f5f87705a.png)

**Comment by jarpy** [comment]
Awesome. Thanks. (And I love the screenshot).

**Comment by cvaldess** [comment]
thanks xeraa, think was 2Gb, will test at home latter and update..

**Comment by cvaldess** [comment]
thanks again xeraa, was docker for mac memory limits, problem solved :)

**Comment by xeraa** [comment]
Great! Happy you got it up and running
