### ISSUE TITLE
Too many redirects with docker.elastic.co/kibana/kibana:5.4.0

### ISSUE THREAD

**Issue by Globegitter** [elastic/kibana-docker#35]
I am just testing an elk setup for our logging system and running into some issue with the officially recommended image `docker.elastic.co/kibana/kibana:5.4.0`. I have a super simple Kubernetes setup, that starts the image behind a load balancer and when trying to access to service on it's IP address Chrome is giving me `ERR_TOO_MANY_REDIRECTS`. However if I switch back to the deprecated image hosted on docker `kibana:5.4.0` all works fine. So I wonder, what is the difference between the two? And why is the new official image doing these redirects? (I am also seeing it tries to go to the path `/login`, which the docker hub image is not doing).

**Comment by dliappis** [comment]
Hello @Globegitter ,

The docker.elastic.co images are [prebundled with x-pack](https://www.elastic.co/guide/en/kibana/current/docker.html) and as a result of that, [x-pack security](https://www.elastic.co/guide/en/x-pack/current/security-getting-started.html), among other features is enabled.

To take advantage of this you should be also running `docker.elastic.co/elasticsearch/elasticsearch:5.4.0` in your cluster.

Relates: https://github.com/elastic/kibana-docker/issues/27

**Comment by Globegitter** [comment]
Hi @dliappis Thanks for the reply and yes, I am still using the hub.docker.com elasticsearch image. But since the issue really seems to lie with X-Pack I think this can be closed in favour of #27.

**Comment by ebuildy** [comment]
any clue to disable this broken feature quickly (maybe a ENV to set when docker run)? 

I got:

```
➜  ~ http --header "http://localhost:5601/"
HTTP/1.1 302 Found
kbn-version: 5.4.1
location: /login?next=%2F

➜  ~ http --header "http://localhost:5601/login?next=%2F"
HTTP/1.1 302 Found
kbn-version: 5.4.1
location: /
```

**Comment by ebuildy** [comment]
How can we disable this **** broken x-pack feature ? (I see redirection from / to login to / to login etc...)

**Comment by dliappis** [comment]
@ebuildy Are both elasticsearch and kibana from docker.elastic.co? Have you disabled x-pack on any of them?

Disabling xpack on elasticsearch requires passing: `- xpack.security.enabled=true`
Disabling xpack on kibana using env vars requires: `- XPACK_SECURITY_ENABLED=true`

See also https://github.com/elastic/kibana-docker/issues/27#issuecomment-296524205 on how to create a customized Kibana image without x-pack.

**Comment by ebuildy** [comment]
Yep sorry, this did the trick, thank you

**Comment by kevinstotz** [comment]
update the 
kibana.yml

1) elasticsearch.url: <your url>
2) server.host: <your ip or hostname>
3) if you changed the password ..update here too
elasticsearch.username: "elastic"
elasticsearch.password: "changeme"

restart the kibana service
