### ISSUE TITLE
kibana-docker user and group ids clash with elasticsearch-docker

### ISSUE THREAD

**Issue by bploetz** [elastic/kibana-docker#42]
The Kibana documentation recommends running Kibana instances on the same hosts that run your Elasticsearch Coordinating Nodes. We run the official Docker images for both Elasticsearch and Kibana.

When you have Kibana configured to write log statements to disk instead of STDOUT (`logging.dest`), and you have that destination directory mounted as a volume on the docker host so that they survive the container's lifetime, this is where you run into a problem. The elasticsearch-docker Dockerfile runs the Elasticsearch process as a user/group "elasticsearch" with uid/gid 1000. The elasticsearch-kibana Dockerfile runs the Kibana process as a user/group "kibana" with the same uid/gid of 1000. Thus we can't create the same "shadow" accounts on the docker host since the uid/gids will clash.

I can obviously work around this issue by creating a custom image, but it would be nice if this just worked out of the box.

**Comment by bploetz** [comment]
I don't use these products, so I'm not sure if it's an issue as well, but I just took a look and both logstash-docker and beats-docker use the same 1000 uid/gid:

https://github.com/elastic/logstash-docker/blob/master/templates/Dockerfile.j2#L20-L24
https://github.com/elastic/beats-docker/blob/master/templates/Dockerfile.j2#L23-L25

**Comment by bquartier** [comment]
Yes, it would be great that the kibana / logstash / elasticsearch images can be run with arbitrary user id (as requested by the Openshift security model) as described here:
https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines
in Support Arbitrary User IDs (see the  uid_entrypoint ).

**Comment by dliappis** [comment]
@bquartier the elasticsearch image should already be uid agnostic and openshift friendly based on the work done in: https://github.com/elastic/elasticsearch-docker/pull/125

**Comment by jarpy** [comment]
Arbitrary user ID support will now ship in version 6.3. Thanks again to @bquartier for the initial patch.

**Comment by jarpy** [comment]
Closing this issue since the fix has shipped.
