### ISSUE TITLE
Kibana unable to connect to Elasticsearch even when ssl keys/certs passed in as env variables

### ISSUE THREAD

**Issue by ocofaigh** [elastic/kibana-docker#45]
**Kibana version**: 5.5.2

**Elasticsearch version**: 2.4.1

**Server OS version**: Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Browser version**: n/a

**Browser OS version**: n/a

**Original install method (e.g. download page, yum, from source, etc.)**: docker pull kibana:latest

**Description of the problem including expected versus actual behavior**: Unable to connect to Elasticsearch at https://<ip_address>:8743
I understand that ES is now proxied by an nginx instance running on the master node alongside ES. It runs on port 8743. This nginx instance has keys/certs that are now needed to get kibana to connect successfully. I was able to get them from the the nginx instance in order to pass in as enviornment variables to the docker run command. But this does not seem to be working. Kibana still cannot connect to ES.

**Steps to reproduce**:
 1. `docker pull kibana:latest`
 2. Get the docker container id: 
![image](https://user-images.githubusercontent.com/29608224/29836440-2b506a52-8ced-11e7-8d0d-680a957da3d9.png)
 3. Grab the keys and certs from the docker container, placing them in /tmp: 
`docker cp $id:/etc/cfc/conf /tmp/kibana`
4. Docker run Kibana, passing in the keys/certs as env variables:
`docker run -d --name kibana -p 5601:5601 -e ELASTICSEARCH_URL="https://<ip_address>:8743" -e ELASTICSEARCH_SSL_CERT="/tmp/kibana/conf/es/server.pem" -e ELASTICSEARCH_SSL_KEY="/tmp/kibana/conf/es/server-key.pem" -e ELASTICSEARCH_SSL_VERIFY="false" -e ELASTICSEARCH_SSL_CA="/tmp/kibana/conf/es/ca.pem" kibana:latest`
5. Log into kibana dashbaord - Unable to connect to Elasticsearch at https://<ip_address>:8743

**Errors in browser console (if relevant)**: Unable to connect to Elasticsearch at https://<ip_address>:8743

**Provide logs and/or server output (if relevant)**:
[kibana_latest_logs.txt](https://github.com/elastic/kibana-docker/files/1261715/kibana_latest_logs.txt)
 (I have replaced the IP address of the server with <ip_address>)

**Comment by jarpy** [comment]
It looks like you are running `kibana:latest`, the image maintained by Docker Inc.

Please try the same thing with the [image from this repository](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

**Comment by ocofaigh** [comment]
@jarpy I am now trying with the image: **docker.elastic.co/kibana/kibana:5.5.2**
I see some of the env variable names have changed in this version, so I have updated my docker run command to this:

`docker run -d --name kibana -p 5601:5601 -e ELASTICSEARCH_URL="https://<ip_address>:8743" -e ELASTICSEARCH_SSL_CERTIFICATE="/opt/deployCfC/kibana/conf/es/server.pem" -e ELASTICSEARCH_SSL_KEY="/opt/deployCfC/kibana/conf/es/server-key.pem" -e ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES="/opt/deployCfC/kibana/conf/es/ca.pem"  -e ELASTICSEARCH_SSL_VERIFICATIONMODE="none" docker.elastic.co/kibana/kibana:5.5.2`

For some bizzare reason, the error in the logs is now:
**'/opt/deployCfC/kibana/conf/es/ca.pem'","error":{"message":"ENOENT: no such file or directory**
Even though this directory and file exists?!
```
[root@pink1-nonha2 es]# pwd
/opt/deployCfC/kibana/conf/es
[root@pink1-nonha2 es]# ls
ca.pem  server-key.pem  server.pem
```
Full log here: [kibana_logs_5.5.2.txt](https://github.com/elastic/kibana-docker/files/1262832/kibana_logs_5.5.2.txt)

**Comment by ocofaigh** [comment]
OK so the reason I was getting the above error was because i had forgot to copy the keys/certs to a directory inside the container. However, once I did that, I still hit the original issue. I have narrowed down the issue though. It seems the env variables on the container are not taking precedence over the values in the kibana.yml file (which they should be). I managed to get this working when I hacked the docker-entrypoint script which creates the yml file in the first place. Any idea why the env variable method is not working?

**Comment by ocofaigh** [comment]
Uh, so its not working because:
{"type":"log","@timestamp":"2017-08-30T11:11:10Z","tags":["status","plugin:xpack_main@5.5.2","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - **This version of Kibana requires Elasticsearch v5.5.2 on all nodes. I found the following incompatible nodes in your cluster: v2.4.1**
