### ISSUE TITLE
Windows variant for Docker images

### ISSUE THREAD

**Issue by sixeyed** [elastic/kibana-docker#46]
It would be good to have a Windows version of the Kibana image, so folks who are in an all-Windows environment can run a containerised Elastic stack. I have a sample [Dockerfile based on Nano Server](https://github.com/sixeyed/dockerfiles-windows/blob/master/kibana/Dockerfile) which works well, and I'm happy to help with the Windows side.

**Comment by jordansissel** [comment]
The first question that comes to mind is how this plays with Windows' licensing. Does Microsoft's licensing permit us to publish and/or host docker images for wider consumption?

**Comment by sixeyed** [comment]
@jordansissel licensing isn't an issue for images - the Windows Server Core and Nano Server images are publicly available, and you can build on them for a public image. The [NATS](https://docs.google.com/document/d/1tAeKfbZI0m-f6SzkKD9SW6IZLYD4dg1Fo8CBkcmZgX8/edit?ts=59b7fe69#heading=h.phthyppwlwmi) official Hub image does this. Licensing is controlled at the usage level - when you run Windows containers, it needs to be on a Windows host and it's the host that need a Windows licence.

**Comment by sixeyed** [comment]
Also... The Windows base layers are considered "foreign layers" so they don't get stored in private registries - i.e. the Windows layers won't be hosted on the Elastic registry, just the layers on top that add Kibana. When users pull they will (transparently) get the Kibana layers from Elastic's registry and the Windows layers from Hub.

**Comment by sixeyed** [comment]
Curious if this is still something you're looking at? I'm working on the 2nd edition of my [Docker on Windows](https://www.amazon.com/Docker-Windows-Elton-Stoneman-ebook/dp/B0711Y4J9K/) book, and it would be great to use official Elastic images rather than my own custom ones. For reference, this is my latest [Dockerfile for Kibana on Windows Server Core](https://github.com/sixeyed/dockerfiles-windows/blob/master/kibana/windowsservercore/Dockerfile).

**Comment by jarpy** [comment]
It's not on the road-map, as I far as I know, @sixeyed. Sorry to be the bearer of bad tidings.

**Comment by jbudz** [comment]
As jarpy mentioned, no plans from our end for now.  We're migrating issues over to elastic/kibana so I reopened at https://github.com/elastic/kibana-docker/issues/46 and will close this one out.
