### ISSUE TITLE
Support for Plugins

### ISSUE THREAD

**Issue by Shifter2600** [elastic/kibana-docker#47]
I have the Plugins folder outside the container and my volume is mapped correctly. How ever how do I install plugins when using the this new docker container. The one I am looking at specifically is https://github.com/nreese/kibana-time-plugin.
I did bin/bash into the container but the OS environment is completely different then the previous official/kibana docker container on DockerHub.
For the install of this Plugin I need git and bower installed on the Container.

**Comment by Shifter2600** [comment]
NM you can close this. I managed to get the plugin by only mapping directly to the plugin itself.
volumes:
       - ./plugins/kibana-time-plugin:/usr/share/kibana/plugins/kibana-time-plugin:rw

**Comment by jarpy** [comment]
Thanks for reporting back.
