### ISSUE TITLE
Support for Multiple Kibana Services in Compose

### ISSUE THREAD

**Issue by Shifter2600** [elastic/kibana-docker#48]
I have docker running in AWS and I have been using the official from Docker Hub until version 5.6.1 which I am in the middle of updating to. I need to run Multiple Kibana's to deal with Instance specific .kibana index's. I know xpack was added to this kibana and I am running these against My Elastic Cloud which does have xpack "b7be70" cluster ID. 

`version: "3"

services:
  kibanatest1:
    image: docker.elastic.co/kibana/kibana:5.6.1
    container_name: test
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
       - ./plugins/kibana-time-plugin:/usr/share/kibana/plugins/kibana-time-plugin:rw
    environment:
      ELASTICSEARCH_URL: https://......
      ELASTICSEARCH_USERNAME: ......
      ELASTICSEARCH_PASSWORD: .......
      KIBANA_INDEX: .kibana-1
      SERVER_DEFAULTROUTE: /app/kibana#/dashboard/7bdc16b0-702d-11e7-88dc-0d54ae3f1f7e?embed=true
    ports:
      - "9999:5601"
  kibanatest2:
    image: docker.elastic.co/kibana/kibana:5.6.1
    container_name: hvms-bi
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
       - ./plugins/kibana-time-plugin:/usr/share/kibana/plugins/kibana-time-plugin:rw
    environment:
      ELASTICSEARCH_URL: https://......
      ELASTICSEARCH_USERNAME: ......
      ELASTICSEARCH_PASSWORD: .......
      KIBANA_INDEX: .kibana-2
      SERVER_DEFAULTROUTE: /app/kibana#/dashboard/7bdc16b0-702d-11e7-88dc-0d54ae3f1f7e?embed=true
    ports:
      - "10001:5601"`

For some reason the xpack will only load successfully on the 1st service. On the kibanatest2 xpack will not load and results in an error on the login screen saying that "Login is currently disabled because the license could not be determined. Please check that Elasticsearch has the X-Pack plugin installed and is reachable, then refresh this page."
Probably due to the errors.
`{"type":"log","@timestamp":"2017-09-26T03:16:28Z","tags":["info","optimize"],"pid":1,"message":"Optimization of bundles for graph, monitoring, ml, kibana, stateSessionStorageRedirect, timelion, login, logout and status_page complete in 206.84 seconds"}
{"type":"log","@timestamp":"2017-09-26T03:16:29Z","tags":["status","plugin:kibana@5.6.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:29Z","tags":["status","plugin:elasticsearch@5.6.1","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:29Z","tags":["status","plugin:xpack_main@5.6.1","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:29Z","tags":["status","plugin:graph@5.6.1","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:29Z","tags":["status","plugin:monitoring@5.6.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:29Z","tags":["reporting","warning"],"pid":1,"message":"Generating a random key for xpack.reporting.encryptionKey. To prevent pending reports from failing on restart, please set xpack.reporting.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2017-09-26T03:16:29Z","tags":["status","plugin:reporting@5.6.1","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:30Z","tags":["info","elasticsearch"],"pid":1,"typeName":"graph-workspace","typeMapping":{"properties":{"description":{"type":"text"},"kibanaSavedObjectMeta":{"properties":{"searchSourceJSON":{"type":"text"}}},"numLinks":{"type":"integer"},"numVertices":{"type":"integer"},"title":{"type":"text"},"version":{"type":"integer"},"wsState":{"type":"text"}}},"message":"Adding mappings to kibana index for SavedObject type \"graph-workspace\""}
{"type":"log","@timestamp":"2017-09-26T03:16:30Z","tags":["status","plugin:xpack_main@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - [remote_transport_exception] [tiebreaker-0000000014][172.17.0.9:19672][indices:admin/mapping/put]","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-09-26T03:16:30Z","tags":["status","plugin:graph@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - [remote_transport_exception] [tiebreaker-0000000014][172.17.0.9:19672][indices:admin/mapping/put]","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-09-26T03:16:30Z","tags":["status","plugin:reporting@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - [remote_transport_exception] [tiebreaker-0000000014][172.17.0.9:19672][indices:admin/mapping/put]","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-09-26T03:16:30Z","tags":["status","plugin:elasticsearch@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - [remote_transport_exception] [tiebreaker-0000000014][172.17.0.9:19672][indices:admin/mapping/put]","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-09-26T03:16:33Z","tags":["info","elasticsearch"],"pid":1,"typeName":"graph-workspace","typeMapping":{"properties":{"description":{"type":"text"},"kibanaSavedObjectMeta":{"properties":{"searchSourceJSON":{"type":"text"}}},"numLinks":{"type":"integer"},"numVertices":{"type":"integer"},"title":{"type":"text"},"version":{"type":"integer"},"wsState":{"type":"text"}}},"message":"Adding mappings to kibana index for SavedObject type \"graph-workspace\""}
{"type":"log","@timestamp":"2017-09-26T03:16:37Z","tags":["info","elasticsearch"],"pid":1,"typeName":"graph-workspace","typeMapping":{"properties":{"description":{"type":"text"},"kibanaSavedObjectMeta":{"properties":{"searchSourceJSON":{"type":"text"}}},"numLinks":{"type":"integer"},"numVertices":{"type":"integer"},"title":{"type":"text"},"version":{"type":"integer"},"wsState":{"type":"text"}}},"message":"Adding mappings to kibana index for SavedObject type \"graph-workspace\""}
{"type":"log","@timestamp":"2017-09-26T03:16:40Z","tags":["info","elasticsearch"],"pid":1,"typeName":"graph-workspace","typeMapping":{"properties":{"description":{"type":"text"},"kibanaSavedObjectMeta":{"properties":{"searchSourceJSON":{"type":"text"}}},"numLinks":{"type":"integer"},"numVertices":{"type":"integer"},"title":{"type":"text"},"version":{"type":"integer"},"wsState":{"type":"text"}}},"message":"Adding mappings to kibana index for SavedObject type \"graph-workspace\""}
{"type":"log","@timestamp":"2017-09-26T03:16:42Z","tags":["status","plugin:security@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from uninitialized to red - [remote_transport_exception] [tiebreaker-0000000014][172.17.0.9:19672][indices:admin/mapping/put]","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:42Z","tags":["security","warning"],"pid":1,"message":"Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2017-09-26T03:16:42Z","tags":["security","warning"],"pid":1,"message":"Session cookies will be transmitted over insecure connections. This is not recommended."}
{"type":"log","@timestamp":"2017-09-26T03:16:42Z","tags":["status","plugin:searchprofiler@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from uninitialized to red - [remote_transport_exception] [tiebreaker-0000000014][172.17.0.9:19672][indices:admin/mapping/put]","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:42Z","tags":["status","plugin:ml@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from uninitialized to red - [remote_transport_exception] [tiebreaker-0000000014][172.17.0.9:19672][indices:admin/mapping/put]","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:43Z","tags":["status","plugin:ml@5.6.1","info"],"pid":1,"state":"yellow","message":"Status changed from red to yellow - Waiting for Elasticsearch","prevState":"red","prevMsg":"[remote_transport_exception] [tiebreaker-0000000014][172.17.0.9:19672][indices:admin/mapping/put]"}
{"type":"log","@timestamp":"2017-09-26T03:16:43Z","tags":["status","plugin:tilemap@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from uninitialized to red - [remote_transport_exception] [tiebreaker-0000000014][172.17.0.9:19672][indices:admin/mapping/put]","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:43Z","tags":["status","plugin:watcher@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from uninitialized to red - [remote_transport_exception] [tiebreaker-0000000014][172.17.0.9:19672][indices:admin/mapping/put]","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:43Z","tags":["status","plugin:grokdebugger@5.6.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:43Z","tags":["status","plugin:upgrade@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from uninitialized to red - [remote_transport_exception] [tiebreaker-0000000014][172.17.0.9:19672][indices:admin/mapping/put]","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:43Z","tags":["status","plugin:ml@5.6.1","info"],"pid":1,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-09-26T03:16:43Z","tags":["status","plugin:console@5.6.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:43Z","tags":["status","plugin:metrics@5.6.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:43Z","tags":["status","plugin:timelion@5.6.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-26T03:16:43Z","tags":["listening","info"],"pid":1,"message":"Server running at http://0:5601"}
{"type":"log","@timestamp":"2017-09-26T03:16:43Z","tags":["status","ui settings","error"],"pid":1,"state":"red","message":"Status changed from uninitialized to red - Elasticsearch plugin is red","prevState":"uninitialized","prevMsg":"uninitialized"}`

On kibanatest1 I do not receive these errors XPack loads fine and I can login with out issues. 

I've even tried removing xpack
`command: [ "/bin/bash", "-c", "/usr/share/kibana/bin/kibana-plugin remove x-pack; /usr/local/bin/kibana-docker" ]`
but I get a error 
`plugin:elasticsearch@5.6.1 | [remote_transport_exception] [tiebreaker-0000000014][111.111.111.111:19672][indices:admin/mapping/put]`

**Comment by Shifter2600** [comment]
This is not specific to docker-compose i get the same results when creating the containers using individual docker run commands.

**Comment by xeraa** [comment]
Is this even Docker related? Have you tried a standalone Kibana instances? They will need to have X-Pack installed.

I might be reading this wrong, but `tiebreaker-0000000014` sounds to me like you are trying to talk to the tiebreaker node instead of one of your Elasticsearch nodes. You probably have a setup with 2AZs and there is a tiebreaker to ensure that there is a majority, but you cannot read or write to that node.

**Comment by Shifter2600** [comment]
> Is this even Docker related? Have you tried a standalone Kibana instances? It will need to have X-Pack installed.

All my other instances are Docker Images 5.4.2 from your previous DockerHub official location. These do not have the Xpack Plugin and as working just fine against the upgraded ElacticCloud instance "b7be70" cluster ID.

> I might be reading this wrong, but tiebreaker-0000000014 sounds to me like you are trying to talk to the tiebreaker node instead of one of your Elasticsearch nodes. You probably have a setup with 2AZs and there is a tiebreaker to ensure that there is a majority, but you cannot read or write to that node.

If the 5.6.1 Docker Contianer is talking to the tiebreaker node this is an issue on your end because I am using the same ELASTICSEARCH_URL: https:// link that is provided on the https://cloud.elastic.co/#clusters/us-west-2 endpoint and is used by all my other docker containers, as well as kibanatest1 which is working in this example. It's only kibanatest2 that is resulting in the issues which makes no sense since the only difference is that it is using a different Port(10001) and KIBANA_INDEX: it's the exact same image and ELASTICSEARCH_ Environment variables.

**Comment by Shifter2600** [comment]
I believe I figured it out but I don't know where to go from here.
I found that it has to do with the KIBANA_INDEX: if I point my index to .kibana-hvms on my cluster it works fine with the docker 5.6.1 w/XPACK installed but if I point to .kibana-hvms-live it doesn't.  My .kibana index in the cluster also works with the docker 5.6.1 w/XPACK installed.

**Comment by Shifter2600** [comment]
Yep I figured it out.

It had to do with the mapping in the .kibana indexes I created like this. 
`POST /_reindex
{
  "source": {
    "index": ".kibana-hvms"
  },
  "dest": {
    "index": ".kibana-hvms-test"
  }
}`

I was creating a copy of the index I had already setup and then making changes to those dashboards for the new Kibana instance. 
What happened was the above only took certain mappings from the source. There were some missing in the dest that caused this issue. 

So the resolution was to copy the mapping from the source that were missing in dest. 

`put .kibana-hvms-test/_mapping/graph-workspace
    {
        "properties": {
          "description": {
            "type": "text"
          },
          "kibanaSavedObjectMeta": {
            "properties": {
              "searchSourceJSON": {
                "type": "text"
              }
            }
          },
          "numLinks": {
            "type": "integer"
          },
          "numVertices": {
            "type": "integer"
          },
          "title": {
            "type": "text"
          },
          "version": {
            "type": "long"
          },
          "wsState": {
            "type": "text"
          }
        }
      }
put .kibana-hvms-test/_mapping/url
{
        "properties": {
          "accessCount": {
            "type": "long"
          },
          "accessDate": {
            "type": "date"
          },
          "createDate": {
            "type": "date"
          },
          "url": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
}
put .kibana-hvms-test/_mapping/timelion-sheet
{
        "properties": {
          "description": {
            "type": "text"
          },
          "hits": {
            "type": "long"
          },
          "kibanaSavedObjectMeta": {
            "properties": {
              "searchSourceJSON": {
                "type": "text"
              }
            }
          },
          "timelion_chart_height": {
            "type": "integer"
          },
          "timelion_columns": {
            "type": "integer"
          },
          "timelion_interval": {
            "type": "text"
          },
          "timelion_other_interval": {
            "type": "text"
          },
          "timelion_rows": {
            "type": "integer"
          },
          "timelion_sheet": {
            "type": "text"
          },
          "title": {
            "type": "text"
          },
          "version": {
            "type": "long"
          }
        }
}
put .kibana-hvms-test/_mapping/index-pattern
{
        "properties": {
          "intervalName": {
            "type": "text"
          },
          "sourceFilters": {
            "type": "text"
          }
        }
      }`

I am not sure if this was a result of the Kibana Docker starting a trial for the xpack items in Platinum. 
Or if the post _reindex has issues with bringing the mapping with it from the Source to the Dest.
This can be closed.

**Comment by xeraa** [comment]
Glad you figured it out and thanks for reporting back :)
