### ISSUE TITLE
Issues with kibana5.5.1 image

### ISSUE THREAD

**Issue by rkumr456** [elastic/kibana-docker#51]
Hi team,

I have pulled kibana 5.5.1 image docker.elastic.co/kibana/kibana:5.5.1.

When i'm strating conatiner locally i'm not getting webui for kibana Dashboard, Please help
![image](https://user-images.githubusercontent.com/30998988/31189386-bcc1d6b8-a955-11e7-9519-218627e64cf1.png)

This isssue is with kibana 5.5.1 only, latest version is working fine.
But we need to use kibana 5.5.1 only please help

**Comment by dliappis** [comment]
Looking at your output it seems you are not using Elastic's own `docker.elastic.co/elasticsearch/elasticsearch:5.5.1` image but rather the one from Docker Hub. Please switch to that one and try again.

**Comment by rkumr456** [comment]
With docker.elastic.co/elasticsearch/elasticsearch:5.5.1 now even ES is not starting.. conatiner get started but automatically Exited after few sec:
![image](https://user-images.githubusercontent.com/30998988/31214351-70f1db02-a9c8-11e7-98a7-37a04f2e4bc8.png)

**Comment by mgreau** [comment]
Hi @rkumr456 

Some few questions so that we can help you more efficiently:

1. Do you have set the `vm.max_map_count` setting as explained in the [official Elastic documentation about Docker configuration](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docker.html#docker-cli-run-prod-mode)
1. Can you give us the **logs** for the containers that died:
   *  `docker logs <container_id>` 
1. The **docker events** can be useful if there is no relevant information in the logs
    * run the `docker events` command in a separate terminal
    * execute the docker command: `docker run  --name ES -P -d  docker.elastic.co/elasticsearch/elasticsearch:5.5.1`  
   * then if this container has died, the `docker events` command should give you more information about what is going on

**Comment by rkumr456** [comment]
Please find docker logs for container that died
![image](https://user-images.githubusercontent.com/30998988/31218591-706a5c1c-a9d8-11e7-8aff-7ffcf97c02f8.png)

**Comment by mgreau** [comment]
> Do you have set the **vm.max_map_count** setting as explained in the [official Elastic documentation about Docker configuration](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docker.html#docker-cli-run-prod-mode)

Looking at the latest lines of your log, it seems that the answer is in the link above ;)

**Comment by rkumr456** [comment]
i tried to run ES container in Development mode using below command 
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.5.1

Container running fine now , but when i'm trying to open webui it is asking for username & password , so what will be user id & password is there some default user id & password i need to pass?

![image](https://user-images.githubusercontent.com/30998988/31220411-f92b31c0-a9dd-11e7-8262-66d185372bd6.png)
![image](https://user-images.githubusercontent.com/30998988/31220466-2a61d92e-a9de-11e7-99ef-a6cf7fa9a5bf.png)

**Comment by rkumr456** [comment]
@mgreau Elastic Search is up now working.
Now i want to run kibana & connect to this elastic search , i have already pulled kibana image
and trying to run but form me kibana Dashboard webui is not coming. Below command i'm using:

![image](https://user-images.githubusercontent.com/30998988/31221218-93324446-a9e0-11e7-8ddf-b975fe56532d.png)

**Comment by mgreau** [comment]
> @mgreau Elastic Search is up now working.

good news.

> kibana Dashboard webui is not coming

What do you mean? Did you try to access to `http://<your-ip>:5601` in a browser? (then connect with `elastic` or `kibana` users with `changeme` as default password)

**Comment by rkumr456** [comment]
Yes i tried with https://10.0.32.8:5601 but Dashboard is not opening.
I'll paste kibana container logs fyi: 

![image](https://user-images.githubusercontent.com/30998988/31222460-ca72558c-a9e4-11e7-849a-81b921e2b476.png)

**Comment by mgreau** [comment]
Can you execute the following command please to see the `ELASTICSEARCH_URL` value:
 
- `docker inspect --format='{{.Config.Env}}' kibana-dev`

**Comment by rkumr456** [comment]
@mgreau It worked Now i was passing http instead of http:. Thankyou!!

**Comment by dliappis** [comment]
@rkumr456 If you don't specify a [user defined network](https://docs.docker.com/engine/userguide/networking/#user-defined-networks) the containers use [the default bridge network](https://docs.docker.com/engine/userguide/networking/#the-default-bridge-network).

With the default bridge network you can't use the container name as an network alias, so you'll need to `docker inspect bridge` to see what's the IP address for the elasticsearch container and use that for your `ELASTICSEARCH_URL`.

This would be done like so:

```
$ docker run -d --name es1 -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.6.2
8525c36c47c6350395a900eb399d2ab9aeaf300ebe9ee8be835b605eb793ba4e

$ docker inspect bridge | grep -A5 es1
                "Name": "es1",
                "EndpointID": "9c960d5b9b36d2f4a9451e51d8173cc488febb9030d1c0de46cc0069099d5832",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }

$ docker run --rm --name kibana1 -p 5601:5601 -e "ELASTICSEARCH_URL=http://172.17.0.2" docker.elastic.co/kibana/kibana:5.6.2

$ curl -u elastic:changeme localhost:5601
<script>var hashRoute = '/app/kibana';
var defaultRoute = '/app/kibana';

var hash = window.location.hash;
if (hash.length) {
  window.location = hashRoute + hash;
} else {
  window.location = defaultRoute;

```


All this becomes much easier with user defined networks, e.g. consider the following docker-compose.
As kibana, by default, is looking for `http://elasticsearch:5601`, here by naming our service as "elasticsearch" the Docker defined network `elasticnet` will automatically create an IP alias with the name elasticsearch, which kibana will use to connect to.

```
version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elasticnet
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.2
    ports:
      - 5601:5601
    networks:
      - elasticnet

networks:
  elasticnet:
```

```
$ docker-compose up -d

$ curl -iu elastic:changeme localhost:5601
HTTP/1.1 200 OK
kbn-name: kibana
kbn-version: 5.6.2
kbn-xpack-sig: 2f97a446bb70fc8ba712f2360fa59b88
cache-control: no-cache
content-type: text/html; charset=utf-8
content-length: 217
accept-ranges: bytes
Date: Thu, 05 Oct 2017 11:17:36 GMT
Connection: keep-alive

<script>var hashRoute = '/app/kibana';
var defaultRoute = '/app/kibana';

var hash = window.location.hash;
if (hash.length) {
  window.location = hashRoute + hash;
} else {
  window.location = defaultRoute;
```

Note that in all the above cases there's no volume defined for the elasticsearch data, so killing the container will wipe away your storage. Please refer to the [elasticsearch docker documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html). You can also find some full stack examples [in this repo](https://github.com/elastic/stack-docker/blob/master/docker-compose.yml).

**Comment by rkumr456** [comment]
@dliappis @mgreau 
Thanks for this information.

I have another question while running the kibana container above we are always passing ELASTICSEARCH_URL in command Line.

What if i want to pass kibana.yml  config file & pem certificates to this kibana 5.5.1 image how i can do this??
Kibana.yml contains ES Url, Username, Password, SSL CA.

One of way i'm trying to do is Creating Below Dockerfile.
FROM docker.elastic.co/kibana/kibana:5.5.1
COPY all_w3-969cert.pem /usr/share/kibana/config/
ADD kibana.yml /usr/share/kibana/config/
From my understanding this docker file will create kibana image with SSL_CA certificates & kibana.yml already in it. So when i run this container there is no need to pass ES Url as argument in cmd becasue all config info is present in kibana.yml
 
I have done all these steps and ran kibana5.5.1 using below command.
docker run --name kibana-dev -p 5601:5601  -d  kibanacustom ( Here i didn't pass ES URL)
kibanacustom : It is image created by above docker file:

Screen Shot 1 Running Conatiner:
![image](https://user-images.githubusercontent.com/30998988/31263626-0f01fe40-aa81-11e7-9bfd-f52f002e7378.png)


Screen Shot2 : Conatiner Logs; From here it seems kibana image is running Successfully.
![image](https://user-images.githubusercontent.com/30998988/31263669-69b13b8a-aa81-11e7-8dd2-fd644e666333.png)

But i'm not able to see kibanaDashboard on localhost:5601 i tried 10.0.32.8:5601(Adress of my VM)
 I checked for ip with below command but here instead of ip i can see path. Some thing is wrong here. Can you please help here
![image](https://user-images.githubusercontent.com/30998988/31263722-ae3b5b64-aa81-11e7-9bff-9f9f35382210.png)

**Comment by jarpy** [comment]
Creating a custom image is fine, there's nothing wrong with that. It's likely that your configuration is not correct, however. You didn't paste your `kibana.yml`, so it's difficult to tell, but I suspect that you may be missing [this line](https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana-oss.yml#L5), which binds the listening socket to all interfaces/addresses. Without that line, Kibana will only respond to requests on the loopback interface, which in this case means that it will only accept requests that originate from _inside the container_.

Next, a few requests. Please:
- Don't paste images of terminals. Text is easier to read, is searchable, and can be used to replicate things for testing. Please just paste the text from your terminal, surrounded by "triple-backticks". Like these -> \`\`\`
- Use [discuss.elastic.co](https://discuss.elastic.co/) for this kind of configuration advice. The GitHub issues system is for tracking and fixing bugs that affect the whole community. Nothing that's happening here is a bug.

**Comment by rkumr456** [comment]
Thanks for looking into this & your Guidance : I have already posted this thing in community but didn't get any feedback so i posted it here.

In my kibana.yml i have added below properties only:
Elastic_Url
UserName
Password
SSl_CA path
The missing line which u pointed is not there in ny kibana.yml.
So what value i should keep for server.host=0 or My VM address (10.0.32.8) Here is my kibana.yml

[kibana.txt](https://github.com/elastic/kibana-docker/files/1361688/kibana.txt)

**Comment by jarpy** [comment]
Why not experiment?

**Comment by rkumr456** [comment]
Worked with 0.  Thankyou so much!!
