### ISSUE TITLE
Install the SENTINL plug-in

### ISSUE THREAD

**Issue by wanghy8166** [elastic/kibana-docker#57]
From the docker.elastic.co/kibana/kibana:5.6.3
I am installing the plugin SENTINL
But the installation cannot continue, and the root password is required

```
root@ubuntu:~# docker exec -it kibana /bin/sh
sh-4.2$ yum install fontconfig freetype                                                                                                                   
Loaded plugins: fastestmirror, ovl
ovl: Error while doing RPMdb copy-up:
[Errno 13] Permission denied: '/var/lib/rpm/__db.001'
You need to be root to perform this command.
sh-4.2$ su - root
Password: 
```

So, what is the root password

**Comment by dliappis** [comment]
There is no defined root password, root login with a password is locked. If you need to execute commands as root via `docker exec` you should specify the user with `docker exec --user 0 -ti kibana /bin/bash`.

```
$ docker exec --user 0 -ti kibana /bin/bash
[root@4ba61de5bbb1 kibana]# 
```

Having said that, I don't see why you need to re-install the `fontconfig` and `freetype` rpm packages, as they are already present in the supplied images:

```
$ docker exec -ti kibana /bin/bash
bash-4.2$ rpm -q fontconfig freetype
fontconfig-2.10.95-11.el7.x86_64
freetype-2.4.11-15.el7.x86_64
```

**Comment by jarpy** [comment]
Also, installing plugins into a running container is probably a poor choice. Much better to extend the image by writing your own Dockerfile, like this:

``` Dockerfile
FROM docker.elastic.co/kibana/kibana:5.6.3
USER root
RUN # whatever you need to
USER kibana
```
