### ISSUE TITLE
Issues building on MacOS

### ISSUE THREAD

**Issue by spalger** [elastic/kibana-docker#68]
Not sure if changes could be committed to make building on MacOS easier, but for others who try it down the road this is what I had to do to get `make build-from-local-artifacts` working:

- install a `timeout` alternative
  - `brew install coreutils`
  - update reference to `timeout` in `Makefile` to `gtimeout`
- docker for mac doesn't support `--network=host`
  - replace `--network=host` with `-p 8000:8000` in `docker run` command that is executing `python3 -m http.server`

PS: the python server isn't killed when the make file exits with an error, so you have to stop it manually each time.

**Comment by jbudz** [comment]
I think we're okay here - the makefile is gone, and we're using COPY or the artifacts repo now instead of over http.  CLosing this out for now.
