### ISSUE TITLE
Add xpack monitoring ssl CA to env mapping

### ISSUE THREAD

**Issue by jguay** [elastic/kibana-docker#69]
kibana 6.1.2, env variable "XPACK_MONITORING_ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES" has no effect so there is error when browsing in monitoring UI (workaround use xpack.monitoring.elasticsearch.ssl.certificateAuthorities in kibana.yml)
can this be added here : 
https://github.com/elastic/kibana-docker/blob/master/build/kibana/bin/kibana-docker

reference doc : https://www.elastic.co/guide/en/kibana/current/monitoring-xpack-kibana.html

**Comment by jarpy** [comment]
Thanks. I've added the fix for this.

It will ship out with 6.1.3, which should be quite soon.
