### ISSUE TITLE
Add missing ENV variable for xpack.apm.ui.enabled

### ISSUE THREAD

**Issue by jakommo** [elastic/kibana-docker#71]
Related to https://github.com/elastic/kibana/issues/15924

Looks like `xpack.apm.ui.enabled` is currently not listed in https://github.com/elastic/kibana-docker/blob/6e8cfe56b623c4ac06583db3a9260cf9d65178a1/build/kibana/bin/kibana-docker#L14 and thus `XPACK_APM_UI_ENABLED` is not working.

**Comment by jarpy** [comment]
I believe that this is now solved by #72.

Please correct me if I'm wrong.

**Comment by jakommo** [comment]
Thanks @jarpy , that looks like good. 
Will this reach the existing 6.1 images or only when there is a 6.1.4?

**Comment by jarpy** [comment]
We can retro-ship it into 6.1.3 is it's really needed, and if 6.1.4 will be a while.

**Comment by jakommo** [comment]
I think it's fine to wait for 6.1.4 as I consider this more of a "cosmetic" thing.
