### ISSUE TITLE
Array Type Environment Variables Treated as Strings

### ISSUE THREAD

**Issue by Ctallon3253** [elastic/kibana-docker#84]
Initially posted this issue in Kibana as I was passing my command line args incorrectly in my testing, https://github.com/elastic/kibana/issues/19773.

I had valued the environment variable in my docker-compose.yml as follows:
`ELASTICSEARCH_REQUESTHEADERSWHITELIST=[mycustomheader,referer]`

I expected both the referer and mycustomheader to be passed to Elasticsearch on requests to it from Kibana, they were not because the configuration was set to an array with a single element in it `[mycustomheader,referer]`.

If I set it as a single value, `ELASTICSEARCH_REQUESTHEADERSWHITELIST=mycustomheader`, the header is passed, but unfortunately I need to include more than one header.

My workaround right now is to set the configuration within the kibana.yml, but it would be helpful if the array type environment variables are able to be properly parsed.

**Comment by jarpy** [comment]
This is an interesting one, thanks.

To a certain extent, I think this is an example of pushing up against the limits of what can reasonably be achieved with environment variables. The primary configuration mechanism for Kibana is `kibana.yml` which, as a YAML document, can be an arbitrarily complex data structure. The secondary configuration mechanism is CLI flags, which is what we are generating from the environment variables.

I see that you had some success in elastic/kibana#19773 by using explicit array indices in your CLI flags, like:

```
./bin/kibana --elasticsearch.requestHeadersWhitelist[0]=mycustomheader --elasticsearch.requestHeadersWhitelist[1]=referer
```

We may be able to reuse that technique (thanks) in our environment variable wrapper. Unfortunately, the [current implementation](https://github.com/elastic/kibana-docker/blob/cdd667d023e42d3129620aa91bb893237684d317/build/kibana/bin/kibana-docker#L144-L155) is in Bash and we may also be pushing up against the limits of what can reasonably be achieved _in that language_.

**Comment by jbudz** [comment]
👍 .  Migrating this over to https://github.com/elastic/kibana/issues/39595. We'll be tracking docker issues in the kibana repo going forward.
