### ISSUE TITLE
Logging to STDOUT is very verbose

### ISSUE THREAD

**Issue by jarpy** [elastic/kibana-docker#87]
The process dumps a lot of output to STDOUT (and thus `docker logs`).

Is it too much? Is it more than we see with the non-container versions of Kibana?

**Comment by tbragin** [comment]
@jbudz Any thoughts on this? Not sure if you've played with the Kibana Docker image yet

**Comment by jbudz** [comment]
I'm going to close this out for now, lets reopen in elastic/kibana if there's further concerns.

non-container versions have a more verbose json output when logging to file than stdout.  In the case of stdout though, and logging.verbose set to false I'd expect it to be the same.
