### ISSUE TITLE
kibana image can't access network

### ISSUE THREAD

**Issue by kneufeld** [elastic/kibana-docker#96]
I don't see how this can be an issue with my infrastructure since other containers work fine:

```
# docker run --rm -it alpine:latest ping -c1 google.com
PING google.com (172.217.0.238): 56 data bytes
64 bytes from 172.217.0.238: seq=0 ttl=51 time=59.334 ms

--- google.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 59.334/59.334/59.334 ms
```

```
# docker run --rm -it docker.elastic.co/kibana/kibana:6.4.0 ping -c1 google.com
ping: socket: Operation not permitted
```

```
# docker run --rm -it --name kibana docker.elastic.co/kibana/kibana:6.4.0
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:23
    at NativeModule.compile (bootstrap_node.js:600:7)
    at NativeModule.require (bootstrap_node.js:545:18)
    at net.js:45:13
    at NativeModule.compile (bootstrap_node.js:600:7)
    at NativeModule.require (bootstrap_node.js:545:18)
    at tty.js:25:13
    at NativeModule.compile (bootstrap_node.js:600:7)
    at NativeModule.require (bootstrap_node.js:545:18)
```

**Comment by xeraa** [comment]
This does not reproduce for me on Mac OS X:

```
$ docker run --rm -it docker.elastic.co/kibana/kibana:6.4.0 ping google.com                                                                                     16:56:35
PING google.com (216.58.207.142) 56(84) bytes of data.
64 bytes from muc11s03-in-f14.1e100.net (216.58.207.142): icmp_seq=1 ttl=37 time=417 ms
64 bytes from muc11s03-in-f14.1e100.net (216.58.207.142): icmp_seq=2 ttl=37 time=504 ms
...
^C
--- google.com ping statistics ---
18 packets transmitted, 18 received, 0% packet loss, time 20485ms
rtt min/avg/max/mdev = 122.481/1035.099/3047.139/1062.122 ms, pipe 3
```

Though my first guess for this issue would be permissions. What's your host operating system, Docker version, and do you have any other specific settings?

Also the second issue doesn't reproduce for me:

```
docker run --rm -it --name kibana docker.elastic.co/kibana/kibana:6.4.0                                                                                       16:57:58
  log   [14:58:28.260] [info][status][plugin:kibana@6.4.0] Status changed from uninitialized to green - Ready
  log   [14:58:28.318] [info][status][plugin:elasticsearch@6.4.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
...
```

**Comment by kneufeld** [comment]
Thank you for looking into this for me.

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

```
# docker --version
Docker version 18.03.1-ce, build 9ee9f40
```

As far as I know there is nothing special going on in my system, as I said I'm running other containers no problem.

**Comment by jarpy** [comment]
I don't think the issue is that the image can't access the network, it's more that the default user in the image can't run ping on your system. The Kibana image runs as the non-privileged user `kibana` (UID 1000) by default. It's not uncommon for non-privileged users to have ping fail because they don't have permission for the appropriate raw socket operations.

Try this and see what happens:

```
docker run --rm -it --user=root docker.elastic.co/kibana/kibana:6.4.0 ping -c1 google.com
```

Running as root will guarantee that you have sufficient privileges. To allow nonprivileged users to run ping, some systems, like my Ubuntu laptop, make the ping binary setuid root:

```
$ stat --format='%A' /bin/ping
-rwsr-xr-x
```

But the CentOS image on which the Kibana image is based doesn't work that way:

```
$ docker run --rm -it centos:7 stat --format='%A' /bin/ping
-rwxr-xr-x
```

Instead, it uses Linux capabilities to grant specific privileges to the ping command:

```
$ docker run --rm -it centos:7 getcap /bin/ping
/bin/ping = cap_net_admin,cap_net_raw+p
```

So, my guess is that the kernel you are running is sufficiently old that it doesn't respect/support the `cap_net_admin` or `cap_net_raw` capability that is set on the binary. Which kernel version are you running?

**Comment by jarpy** [comment]
Hmm... `cap_net_raw` and `cap_net_admin` are pretty old-school, so I would expect them to be in your kernel. I'm still interested in what happens when you run as root, though.

[This ](https://github.com/nodejs/help/issues/948) is also interesting, and rather surprising!

**Comment by jarpy** [comment]
I see that the Alpine image has neither the setuid bit, nor `cap_net_*` set on `/bin/ping`, and non-privileged users can't run ping there either.

```
$ docker run --rm -it alpine:latest
/ # adduser -D jarpy
/ # su - jarpy
a01de0ebc9ba:~$ ping google.com
PING google.com (172.217.167.110): 56 data bytes
ping: permission denied (are you root?)
```
Of course, this does not explain why Node is crashing, but I wan't to focus on ping first.

**Comment by kneufeld** [comment]
My kernel version is `4.4.0-128-generic`. I had tried  `cap_net_raw` and `cap_net_admin` and `cap_net_all` to zero effect.

I had noticed that the image ran as `kibana` user and suspected that was the problem but I wasn't aware of the `--user=root` switch. Running with `--user=root` solves the ping and `kibana` crashing problem.

So it looks like there's some sort of incompatibility between the `Ubuntu 16.04` kernel and the `Centos` based docker image. Since the `user` switch unblocks me I'll just use that for now but would love to hear about a _"better"_ solution.

I can close this issue if you'd like?

**Comment by jarpy** [comment]
Thanks for the update and for the interesting problem!

I think it would be best to pursue a proper explanation through the Centos image project. To be honest, I'm quite at a loss now.

If you do discover a solution, I'd be very grateful if you report back.

Thanks.
